# -*- coding: utf-8 -*-
"""LogisticReg3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jPMIzNJjYEDh7h-rXkU5VPaRkYev46SY
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

dataset = pd.read_csv("data.csv")
print(dataset)

dataset['Brought_Insurance'].replace({'no':'0', 'yes':'1'}, inplace=True)

print(dataset)

plt.scatter(x='Age', y='Brought_Insurance', data=dataset)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(dataset[['Age']],dataset['Brought_Insurance'], test_size= 0.2)

len(x_train)

len(x_test)

x_train

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)

model.predict(x_test)

model.predict([[10]])